package com.myspace.hellotesting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExideTesting implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String as;

	public ExideTesting() {
	}

	public java.lang.String getAs() {
		return this.as;
	}

	public void setAs(java.lang.String as) {
		this.as = as;
	}

	public ExideTesting(java.lang.String as) {
		this.as = as;
	}

}