package com.myspace.hellotesting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExideTesting implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExideTesting() {
    }




}