package com.myspace.hellotesting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class hello implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer fedf;

	public hello() {
	}

	public java.lang.Integer getFedf() {
		return this.fedf;
	}

	public void setFedf(java.lang.Integer fedf) {
		this.fedf = fedf;
	}

	public hello(java.lang.Integer fedf) {
		this.fedf = fedf;
	}

}